authorname: Evgenii Frikin

draft: false

project:
  type: website
  preview:
    host: 0.0.0.0
    port: 6411
  # resources:

execute:
  freeze: auto

metadata-files:
  - RFDs/_quarto.local.yaml

title-meta: "Evgenii Frikin"
description-meta: "Personal blog"

website:
  title: "Egenii Frikin's Blog"
  description: "Personal blog"
  # favicon: images/favicon.png
  site-url: "https://blog.evgenii.us"
  repo-url: "{{< env GITHUB_SERVER_URL >}}/{{< env GITHUB_REPOSITORY >}}"
  repo-branch: main
  page-navigation: true

  open-graph: true
  twitter-card: false

  # bread-crumbs: true
  # repo-actions: issue
  # image: images/logo.png
  navbar:
    pinned: true
    title: "&nbsp;&nbsp;{{< meta authorname >}}<span class='icon-line'></span>My Reflections"
    left:
      - text: posts
        href: posts
        icon: card-text
      - text: publications&talks
        href: publications-and-talks
        icon: share-fill

  search: false

  page-footer:
    center: |
      <span class="faux-block"><a href='{{< env GITHUB_SERVER_URL >}}/{{< env GITHUB_REPOSITORY >}}/tree/{{< env QUARTO__TAG >}}'> {{< fa brands github >}} {{< env QUARTO__TAG >}}</a></span><br>
      <span class="faux-block">{{< fa brands creative-commons-share >}} {{< env QUARTO__CURRENT_YEAR >}} {{< meta authorname >}}</span>
    border: false
format:
  html:
    theme: themes/dark.scss
      # light: assets/ek-theme-light.scss
      # dark: assets/ek-theme-dark.scss
    css:
      - themes/custom.css
    code-block-border-left: true
    highlight-style: themes/custom.theme
      # light:
      # dark:
    smooth-scroll: true
    link-external-newwindow: true
    toc: false
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    include-in-header: _includes/seo.html

editor: source

