---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarto-envs
data:
 QUARTO__CURRENT_YEAR: "2024"
 QUARTO__TAG: 0.0.0
 GITHUB_SERVER_URL: https://github.com
 GITHUB_REPOSITORY: efrikin
---
apiVersion: v1
kind: Pod
metadata:
  name: quarto
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: preview
      image: ghcr.io/quarto-dev/quarto:1.8.24
      command:
        - quarto
        - preview
      envFrom:
        - configMapRef:
            name: quarto-envs
            optional: false
      workingDir: /srv
      ports:
        - containerPort: 6411
          hostPort: 6411
      volumeMounts:
        - name: source
          mountPath: /srv:z
        - name: certs
          ## Note: hostPath volume types created by kube play is given an
          ## SELinux shared label (z), bind mounts are not relabeled
          ## (use chcon -t container_file_t -R <directory>).
          ## https://docs.podman.io/en/v5.5.1/markdown/podman-kube-play.1.html
          ## sudo chcon -t container_file_t /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          mountPath: /etc/ssl/certs/ca-certificates.crt
        - name: d2
          mountPath: /bin/d2:Z
  volumes:
    - name: source
      hostPath:
        path: ./
        type: Directory
    - name: d2
      hostPath:
        path: asserts/d2
        type: File
    - name: certs
      hostPath:
        path: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
        type: File



