name: 'Quarto render and publish site to GitHub Pages'

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    if: startsWith(github.ref, 'refs/tags/')

jobs:
  quarto:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      - name: Prepare to build
        run: |
          echo "QUARTO__CURRENT_YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "QUARTO__TAG=${GITHUB_REF#refs/*/*}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ env.QUARTO__TAG }}

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

